In [9]:
import numpy as np

X = np.array(([2,9], [1,5], [3,9]))
Y = np.array(([92], [86], [89]))

X = X/np.amax(X, axis=0)
Y = Y/100

In [10]:
class NeuralNetwork(object):
    def __init__(self):
        self.input_layers_size: 2
        self.hidden_layers_size: 3
        self.output_layers_size: 1
            
        self.w1 = np.random.rand(2,3)
        self.w2 = np.random.rand(3,1)
        
    def forward(self,X):
        self.z = np.dot(X,self.w1)
        self.z2 = 1/(1+np.exp(-self.z))
        self.z3 = np.dot(self.z2, self.w2)
        
        output = 1/(1+np.exp(-self.z3))
        return output
    
    def backward(self,X,Y,predicted_output):
        self.output_error = Y - predicted_output
        self.output_delta = self.output_error * (predicted_output * (1 - predicted_output))
        
        self.z2_error = self.output_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error * (self.z2 * (1 - self.z2))
        
        self.w1 += learning_rate * X.T.dot(self.z2_delta)
        self.w2 += learning_rate * self.z2.T.dot(self.output_delta)

In [11]:
NN = NeuralNetwork()

In [12]:
learning_rate = 0.1

for i in range(30):
    print("Epoch: ",i)
    print("Learning Rate:\n", learning_rate)
    print("Input\n", str(X) )
    print("Actual Output:\n", str(Y))
    predicted_output = NN.forward(X)
    print("Predicted output:\n", predicted_output)
    print("Loss:\n", str(np.mean(np.square(Y - predicted_output))))
    print("\n\n")
    
    NN.backward(X,Y,predicted_output)

Epoch:  0
Learning Rate:
 0.1
Input
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         1.        ]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted output:
 [[0.65996493]
 [0.64369459]
 [0.66826417]]
Loss:
 0.05452434830198974



Epoch:  1
Learning Rate:
 0.1
Input
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         1.        ]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted output:
 [[0.66471917]
 [0.64795857]
 [0.67324826]]
Loss:
 0.05237039604850922



Epoch:  2
Learning Rate:
 0.1
Input
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         1.        ]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted output:
 [[0.669323  ]
 [0.65209188]
 [0.67807083]]
Loss:
 0.05032624003452362



Epoch:  3
Learning Rate:
 0.1
Input
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         1.        ]]
Actual Output:
 [[0.92]
 [0.86]
 [0.89]]
Predicted output:
 [[0.67378209]
 [0.65609936]
 [0.68273805]]
Loss:
 0.04838541500377903



Epoch:  4
Learni